[mgr]
cwd = { fg = "#e78a4e" }

hovered         = { fg = "#a9a665", bg = "#504945" }
preview_hovered = { underline = true }

find_keyword  = { fg = "#ca3433", italic = true }
find_position = { fg = "#ca3433", bg = "reset", italic = true }

marker_selected = { fg = "#7daea3", bg = "#7daea3" }
marker_copied   = { fg = "#d8a657", bg = "#d8a657" }
marker_cut      = { fg = "#ca3433", bg = "#ca3433" }

tab_active   = { fg = "#a9a665", bg = "#504945" }
tab_inactive = { fg = "#a9a665", bg = "#3c3836" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#504945" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#504945", bg = "#504945" }

progress_label  = { fg = "#d4be98", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error  = { fg = "#ea6962", bg = "#3c3836" }

permissions_t = { fg = "#504945" }
permissions_r = { fg = "#a9a665" }
permissions_w = { fg = "#fb4934" }
permissions_x = { fg = "#a9a665" }
permissions_s = { fg = "#504945" }

[mode]
normal_main = { fg = "#282828", bg = "#d8a657", bold = true }
normal_alt = { fg = "#282828", bg = "#a9a665", bold = true }

select_main = { fg = "#282828", bg = "#b8bb26", bold = true }
select_alt = { fg = "#282828", bg = "#b8bb26", bold = true }

unset_main  = { fg = "#282828", bg = "#d3869b", bold = true }
unset_alt  = { fg = "#282828", bg = "#d3869b", bold = true }

[input]
border   = { fg = "#d4be98" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#504945" }
active   = { fg = "#fe8019" }
inactive = {}

[tasks]
border  = { fg = "#504945" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#3c3836" }
cand            = { fg = "#83a598" }
rest            = { fg = "#928374" }
desc            = { fg = "#fe8019" }
separator       = "  "
separator_style = { fg = "#504945" }

[help]
on      = { fg = "#fe8019" }
exec    = { fg = "#83a598" }
desc    = { fg = "#928374" }
hovered = { bg = "#504945", bold = true }
footer  = { fg = "#3c3836", bg = "#a89984" }

[filetype]

rules = [
    { mime = "image/*", fg = "#7daea3" },

    { mime = "video/*", fg = "#89b482" },
    { mime = "audio/*", fg = "#89b482" },

    { mime = "application/zip",             fg = "#e78a4e" },
    { mime = "application/gzip",            fg = "#e78a4e" },
    { mime = "application/x-tar",           fg = "#e78a4e" },
    { mime = "application/x-bzip",          fg = "#e78a4e" },
    { mime = "application/x-bzip2",         fg = "#e78a4e" },
    { mime = "application/x-7z-compressed", fg = "#e78a4e" },
    { mime = "application/x-rar",           fg = "#e78a4e" },

    { name = "*", fg = "#d4be98" },
    { name = "*/", fg = "#a9a665" }
]
